excluded: # paths to ignore during linting. Takes precedence over `included`.
- Carthage
- Pods
disabled_rules:
- force_cast
- line_length
- trailing_whitespace
force_try: warning
nesting:
    type_level: 3

